name: Run start.py every 5 minutes on weekdays

on:
  schedule:
    - cron: "*/5 23,0-3,6-12 * 1,3-6,9-12 1-5"
  workflow_dispatch:

concurrency:
  group: scheduled-task
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true    # 👈 新增这行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python start.py
        env:
          SESSION: ${{ secrets.SESSION }}
          # EMAIL_USER: ${{ secrets.EMAIL_USER }}
          # EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          # TO_EMAIL: ${{ secrets.TO_EMAIL }}
          # EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          # EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          AI_KEY: ${{ secrets.AI_KEY }}
          ENNCY_KEY: ${{ secrets.ENNCY_KEY }}
          FILTERED_COURSES: ${{ secrets.FILTERED_COURSES }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto update logs" || echo "No changes to commit"
          git push origin $(git rev-parse --abbrev-ref HEAD)
