name: 我要自动签到答题
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  checkin:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: 安装依赖
        run: python -m pip install -r requirements.txt  # 👈 修复点

      - name: 启动签到
        run: python start.py
